server:
  port: 80

spring:
  application:
    name: order-service

eureka:
  client:
    #表示是否将自己注册进Eureka Server默认为true
    register-with-eureka: true
    #是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，集群必须配置为true，才能配合ribbon负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群
