server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh  #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**


eureka:
  instance:
    instance-id: cloud-gateway-service
    prefer-ip-address: true
  client:
    #表示是否将自己注册进Eureka Server默认为true
    register-with-eureka: true
    #是否从Eureka Server抓取已有的注册信息，默认为true，单节点无所谓，集群必须配置为true，才能配合ribbon负载均衡
    fetch-registry: true
    service-url:
      #http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群

